name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      env:
        appSid: ${{secrets.appSid}}
        appKey: ${{secrets.appKey}}
        apiBaseUrl: "https://api-qa.aspose.cloud"
      run: |
        sed 's/replaceAppKey/${appKey}/g' tests/phpunit.xml > tests/phpunit.xml
        sed 's/replaceAppSid/${appSid}/g' tests/phpunit.xml > tests/phpunit.xml
        sed 's/replaceApiBaseUrl/${apiBaseUrl}/g' tests/phpunit.xml > tests/phpunit.xml
        vendor/phpunit/phpunit/phpunit --configuration tests/phpunit.xml tests
